author: Max Romanyuta
name: Simple Dotenv
description: This action will read the .env file and add variables to GITHUB_ENV
branding:
  icon: box
  color: white
inputs:
  path:
    description: The path to the folder where the .env file is located
    required: false
    default: './'
  mode:
    description: The mode for load the .env file
    required: false
    default: ''
  load-mode:
    description: Sets whether the program should fail when the .env file is not present (strict) or continue (skip)
    required: false
    default: 'strict'
runs:
  using: node20
  main: ./dist/index.js
